const proudct = [

  {
    id: 47723415142589,
    name: "Torino Heritage",
    desc: "Comfort Built Impress Designed",
    price: 149,
    oldprice: 200,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Genuine Leather",
    mainimg: "./file/1/5.webp",
    modelwearmob:"./file/1/20.avif",
    modelwearpc:"./file/1/10.avif",
    shortdesc: "Premium Leather with Lightweight And Comfort derby",
    longdesc: "Premium Leather with Lightweight Comfort and Contemporary Appeal",
    model:"All Day Comfort Derby",
    modelimg:"./file/1/5.webp",
    techdesc1:"A modern genuine leather Derby with clean lines, refined craftsmanship, and effortless versatility for every occasion.",
    techdesc2:"This isn't just a Derby It's how you want to be seen. Crafted from black leather with flawless precision for the man who stands apart naturally.",
    Upper:"Premium smooth natural leather with a refined satin finish, offering exceptional durability and a soft, adaptive fit .",
    Inner:"Ultra-soft natural leather lining for maximum breathability and all-day comfort .",
    Insole:"Cushioned leather-covered insole with high-density foam for premium shock absorption .",
    Outsole:"Lightweight, heavy-duty rubber lug sole (Chunky Design) providing superior grip, stability, and a bold modern look .",
    modelname:"Derby",
    modeldesc:"Derby Shoes Effortless Style Everyday Confidence Derby shoes are more than just footwear they are a clean confident choice The open lacing design gives you a comfortable fit that feels natural all day They work for everything from work to casual outings with a timeless look that always fits in Simple details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Derby shoes give you style without overthinking it Derby where classic style meets everyday wear",
    title:"Vonaldo Torino Heritage Derby | Premium Italian Leather – All-Day Comfort & Timeless Style",
    metadesc:"Elevate your style with Torino Heritage Derby shoes. Crafted from Premium Italian Leather with a shock-absorbing insole and extra-light chunky sole for all-day comfort and effortless confidence",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/1/5.webp",
          "./file/1/2.webp",
          "./file/1/3.webp",
          "./file/1/7.webp",
          "./file/1/6.webp",
          "./file/1/1.webp",

        ],
        colorimg:"./file/1/1.webp",
        sizes: [
          { size: 6, id: 48224937050301 },
          { size: 6.5, id: 48224936984765 },
          { size: 7.5, id: 48224937181373 },
          { size: 8, id: 48224937115837 },
          { size: 8.5, id: 48224936820925 },
          { size: 9, id: 48224936755389 },
          { size: 9.5, id: 48224936919229 },
        ],
      },
    ],
  },


    {
    id: 47726535377085,
    name: "Bellacero",
    desc: "Seen Once Remembered Always",
    price: 149,
    oldprice: 200,
    vare:"Essential",
        sizeguide:"./icons/main.webp",
listcolor:"#f5f3ef",
    material:"Premium Polished Leather",
    mainimg: "./file/6/3.webp",
    modelwearmob:"./file/6/20.avif",
    modelwearpc:"./file/6/10.avif",
    shortdesc: "Crafted for those who value details and confidence",
    longdesc: "Created for people who notice details and wear confidence naturally",
model:"Built For Everyday Confidence Derby",
    modelimg:"./file/6/3.webp",
techdesc1:"Crafted for movement between formal structure and everyday ease this shoe blends refined materials with a clean modern finish for a presence that feels natural in every setting.",

techdesc2:"Every step carries intention this shoe shapes your presence through clean design and grounded strength.",
    Upper:"Premium gloss patent leather featuring a clean plain-toe design and classic open lacing for a bold, contemporary look",
    Inner:"Soft natural nappa leather lining for exceptional comfort, reduced friction, and enhanced breathability",
   Insole:"Anatomical leather footbed with a shock-absorbing layer, designed to support the foot and provide all day comfort",
    Outsole:"Extra-light chunky lug sole made from advanced PU/TPU materials, delivering strong grip, durability, and a bold statement without added weight",
    modelname:"Derby",
    modeldesc:"Derby Shoes Effortless Style Everyday Confidence Derby shoes are more than just footwear they are a clean confident choice The open lacing design gives you a comfortable fit that feels natural all day They work for everything from work to casual outings with a timeless look that always fits in Simple details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Derby shoes give you style without overthinking it Derby where classic style meets everyday wear",
title:"Vonaldo Bellacero Derby Shoes | Premium Gloss Leather & Modern Confidence",
metadesc:"Discover Bellacero Derby shoes by Vonaldo. Crafted from premium polished gloss leather with soft nappa lining, shock-absorbing insole, and lightweight chunky sole for all-day comfort, refined style, and confident modern elegance",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/6/3.webp",
          "./file/6/5.webp",
          "./file/6/2.webp",
          "./file/6/1.webp",
        ],
        colorimg:"./file/6/30.avif",
        sizes: [
          { size: 6, id: 48220434170045 },
          { size: 6.5, id: 48220434202813 },
          { size: 7.5, id: 48220434235581 },
          { size: 8, id: 48220434268349 },
          { size: 8.5, id: 48220434301117 },
          { size: 9, id: 48220434333885 },
          { size: 9.5, id: 48220434366653 },
          { size: 10.5, id: 48220434399421 },
          { size: 11, id: 48220434432189 },
        ],
      },
    ],
  },


  {
    id: 47726868070589,
    name: "Varenza Elite",
    desc: "Comfort Built Impress Designed",
    price: 169,
    oldprice: 230,
    vare:"New Collection",
        sizeguide:"./icons/main.webp",
listcolor:"#f5f3ef",
    material:"Premium Patent Leather",
    mainimg: "./file/4/12.webp",
    modelwearmob:"./file/4/10.avif",
    modelwearpc:"./file/4/20.avif",
    shortdesc: "Glossy leather elevated with bold, commanding presence",
    longdesc: "Premium Derby Shoe with Polished Sophistication and Commanding Presence",
    model:"All Day Comfort Derby",
    modelimg:"./file/4/19.webp",
    techdesc1:"Some shoes ask to be noticed. This one doesn't have to — its shine speaks first. A polished Derby for the man whose presence never needs an introduction.",
    techdesc2:"There's a version of you that doesn't explain himself. This silhouette was built for him — sharp enough to cut through a room, quiet enough to never prove it.",
  Upper: "High gloss black patent leather with a premium finish, featuring precise panel stitching and a classic cap-toe design, blending formal elegance with a bold modern aesthetic.",
  Inner: "Premium soft natural leather lining for optimal breathability and reduced friction, ensuring maximum comfort during extended wear.",
  Insole: "Leather lined footbed with a shock absorbing core, ergonomically designed to support the arch and distribute pressure evenly for all day comfort.",
  Outsole: "Durable chunky rubber lug sole with a matte finish, engineered for exceptional traction and slip resistance, adding a strong structural character to the luxurious design.",
    modelname: "Derby",
    modeldesc:"Derby Shoes Effortless Style Everyday Confidence Derby shoes are more than just footwear they are a clean confident choice The open lacing design gives you a comfortable fit that feels natural all day They work for everything from work to casual outings with a timeless look that always fits in Simple details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Derby shoes give you style without overthinking it Derby where classic style meets everyday wear",
title:"Vonaldo Varenza Elite Derby | Luxury Gloss Leather & Modern Statement Design",

metadesc:"Step into bold elegance with Varenza Elite Derby shoes. Crafted from premium gloss leather with a shock-absorbing footbed and durable chunky lug sole for confident all-day comfort and modern luxury styling",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/4/12.webp",
          "./file/4/6.webp",
          "./file/4/21.webp",
          "./file/4/11.webp",
          "./file/4/9.webp",
          "./file/4/18.webp",
        ],
        colorimg:"./file/4/30.webp",
        sizes: [
          { size: 6, id: 47726868070589 },
          { size: 6.5, id: 47726868037821 },
          { size: 7.5, id: 47726868005053 },
          { size: 8, id: 47726867972285 },
          { size: 8.5, id: 47726867939517 },
          { size: 9, id: 47726867906749 },
          { size: 9.5, id: 47726867873981 },
          { size: 10, id: 47726867873981 },
        ],
      },
    ],
  },





    {
    id: 47726936490173,
    name: "Urban Heritage",
    desc: "Where the Lights Turn Gold",
    price: 169,
    oldprice: 230,
    vare:"Essential",
        sizeguide:"./icons/main.webp",
listcolor:"#f5f3ef",
    material:"Genuine Patent Leather",
    mainimg: "./file/5/4000.webp",
    modelwearmob:"./file/5/20.avif",
    modelwearpc:"./file/5/10.avif",
shortdesc:"Premium patent leather Derby, sophisticated and confident",
longdesc:"Premium black patent leather Derby embodying sophistication and confidence",
model:"Smart Modern Comfort Derby",
modelimg:"./file/5/4.webp",
techdesc1:"Some shoes are made for the office. This one is made for the moment you walk out of the hotel lobby, and the night decides it likes you",
techdesc2: "Sleek patent leather Derby with a refined silhouette, engineered for all-day comfort and built for the moments after dark",
Upper:"Premium high gloss patent leather featuring distinct moc toe stitching and open lacing for a bold modern look",
Inner:"Soft natural nappa leather lining ensuring exceptional comfort reduced friction and enhanced breathability",
Insole:"Anatomical footbed with a shock absorbing layer designed to support the foot and provide all day comfort",
Outsole:"Extra light chunky lug sole delivering strong grip reliable durability and a bold statement without added weight",
    modelname:"Derby",
    modeldesc:"Derby Shoes Effortless Style Everyday Confidence Derby shoes are more than just footwear they are a clean confident choice The open lacing design gives you a comfortable fit that feels natural all day They work for everything from work to casual outings with a timeless look that always fits in Simple details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Derby shoes give you style without overthinking it Derby where classic style meets everyday wear",
title:"Vonaldo Urban Heritage Derby Shoes | Premium Gloss Leather & Modern Comfort",
metadesc:"Discover Urban Heritage Derby shoes by Vonaldo. Crafted from premium polished gloss leather with a shock-absorbing footbed and lightweight chunky lug sole for bold everyday style, modern elegance, and all-day comfort",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/5/4000.webp",
          // "./file/5/5.jpg",
          "./file/5/2.webp",
          "./file/5/6.webp",


        ],
        colorimg:"./file/5/40.webp",
        sizes: [
          { size: 6.5, id: 47726936490173 },
          { size: 7.5, id: 47726936555709 },
          { size: 8, id: 47726936522941 },
          { size: 8.5, id: 47726936391869 },
          { size: 9, id: 47726936359101 },
          { size: 9.5, id: 47726936457405 },
          { size: 10.5, id: 47726936424637 },
        ],
      },
    ],
  },


     {
    id: 47727296544957,
    name: "Eclipse Garnet",
    desc: "Black in the shade, Garnet in the light",
    price: 169,
    oldprice: 230,
    vare:"New Collection",
        sizeguide:"./icons/main.webp",
listcolor:"#f5f3ef",
    material:"Premium Polished Leather",
    mainimg: "./file/18/2.webp",
    modelwearmob:"./file/18/10.avif",
    modelwearpc:"./file/18/10.avif",
    shortdesc: "Designed for versatile style, crafted with modern character",
    longdesc: "Premium Burgundy Derby Shoe with modern edge and sleek presence",
    model:"Modern Style Comfort Derby",
    modelimg:"./file/18/2.webp",
techdesc1:"Not made to stand out — made to be remembered. This Derby moves easy, sits quiet, and lingers long after the room has forgotten everyone else.",

techdesc2:"Burgundy doesn't shout. It waits for the light, then takes the room without a sound.",
    Upper:"Crafted from premium leather with a glossy finish and a striking burnished toe effect, featuring classic open lacing and a heel pull tab for everyday ease",
    Inner:"Soft natural nappa leather lining for exceptional comfort, reduced friction, and enhanced breathability",
    Insole:"Anatomical leather footbed with a shock-absorbing layer, designed to support the foot and provide all day comfort.",
    Outsole:"Extra-light, smooth chunky sole made from advanced PU/TPU materials, delivering durability, elevated height, and a modern statement without added weight.",
    modelname:"Derby",
    modeldesc:"Derby Shoes Effortless Style Everyday Confidence Derby shoes are more than just footwear they are a clean confident choice The open lacing design gives you a comfortable fit that feels natural all day They work for everything from work to casual outings with a timeless look that always fits in Simple details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Derby shoes give you style without overthinking it Derby where classic style meets everyday wear",
title:"Vonaldo Eclipse Garnet Burgundy Derby | Premium Polished Leather Shoes – Modern Elegance & Comfort",

metadesc:"Shop Eclipse Garnet Burgundy Derby shoes by Vonaldo. Made from premium polished leather with soft nappa lining, shock-absorbing insole, and lightweight chunky sole for all-day comfort, modern elegance, and confident formal style",
    colors: [
      {
        color: "Burgundy",
        imgs: [
          "./file/18/2.webp",
          "./file/18/4.webp",
          "./file/18/20.webp",
          "./file/18/5.webp",
        ],
        colorimg:"./file/18/25.webp",
        sizes: [
          { size: 6, id: 47727296544957 },
          { size: 6.5, id: 47727296512189 },
          { size: 7.5, id: 47727296479421 },
          { size: 8, id: 47727296446653 },
          { size: 8.5, id: 47727296413885 },
          { size: 9, id: 47727296381117 },
          { size: 9.5, id: 47727296348349 },
        ],
      },
    ],
  },
    {
    id: 47729010147517,
    name: "Cosimo Nero",
    desc: "Designed To Shine Built To Last",
    price: 149,
    oldprice: 200,
    vare:"Essential",
    sizeguide:"./file/2/100.avif",
    listcolor:"#f3f1ee",
    material:"Premium leather patent or matte",
    mainimg: "./file/2/3.webp",
    modelwearmob:"./file/2/20.avif",
    modelwearpc:"./file/2/10.avif",
    shortdesc: "Refined Oxford leather, elegance and everyday comfort",
    longdesc: "Refined Oxford leather delivering timeless elegance and everyday comfort",
    model:"Modern Thick Sole Oxford",
    modelimg:"./file/2/6.webp",
    techdesc1:"Combining premium leather craftsmanship with timeless design, this shoe makes a quiet statement of status — effortless in the boardroom, unmistakable in smart casual.",
    techdesc2:"A refined expression of modern style, this shoe carries quiet confidence and unmistakable presence in every step.",
    Upper:"Available in premium natural leather with a refined finish or striking high gloss patent leather featuring classic closed lacing for a structured and timeless look",
    Inner:"Soft natural nappa leather lining for exceptional comfort, reduced friction, and enhanced breathability",
    Insole:"Anatomical leather footbed with a shock-absorbing layer, designed to support the foot and provide all day comfort",
    Outsole:"Extra-light chunky lug sole made from advanced PU/TPU materials, delivering strong grip, durability, and a bold statement without added weight",
    modelname:"Oxford",
    modeldesc:"Oxford Shoes Refined Elegance Everyday Sophistication Oxford shoes are more than just footwear they are a sleek polished choice The closed lacing profile gives you a secure fit that feels tailored all day They elevate everything from suits to smart casual looks with a classic edge that always stands out Refined stitching premium leathers and a sleek silhouette make them easy to rely on Elegant powerful and always on point Oxford shoes give you grace without overthinking it Oxford where formal grace meets modern wear",
    title:"Vonaldo Cosimo Nero Oxford Shoes | Premium Italian Leather & Chunky Sole",
    metadesc:"Discover Cosimo Nero Oxford shoes by Vonaldo. Crafted from premium Italian leather with a lightweight chunky sole, shock-absorbing comfort, and a bold modern silhouette for formal and smart casual wear",
    colors: [
      {
        color: "Glossy",
        imgs: [
          "./file/2/3.webp",
          // "./file/2/90.webp",
          "./file/2/8.webp",
          "./file/2/1.webp",
          "./file/2/6.webp",
          // "./file/2/9.webp",
          "./file/2/7.webp",
          "./file/2/5.webp",
        ],
        colorimg:"./file/2/60.webp",
        sizes: [
          { size: 5.5, id: 47729010147517 },
          { size: 6, id: 47729010114749 },
          { size: 6.5, id: 47729010213053 },
          { size: 7.5, id: 47729010180285 },
          { size: 8, id: 47729010016445 },
          { size: 8.5, id: 47729009983677 },
          { size: 9, id: 47729010081981 },
          { size: 9.5, id: 47729010049213 },
          { size: 10, id: 47729009885373 },
        ],
      },
      {
        color: "Matte",
        imgs: [
          "./file/3/6.webp",
          "./file/3/5.webp",
          "./file/3/3.webp",
          "./file/3/2.webp",
          "./file/3/4.webp",
        ],
        colorimg:"./file/3/20.webp",
        sizes: [
          { size: 5.5, id: 47729009852605 },
          { size: 6, id: 47729009852605 },
          { size: 6.5, id: 47729009918141 },
          { size: 7.5, id: 47729009754301 },
          { size: 8, id: 47729009721533 },
          { size: 8.5, id: 47729009819837 },
          { size: 9, id: 47729009787069 },
          { size: 9.5, id: 47729010278589 },
          { size: 10, id: 47729010245821 },
        ],
      },
    ],
  },
   





  
    {
    id: 47729030791357,
    name: "Capri comfort",
    desc: "The heart of pure design",
    price: 179,
    oldprice: 240,
    vare:"Essential",
    sizeguide:"./file/32/10.png",
    listcolor:"#f5f3ef",
    material:"Premium Genuine Leather",
    mainimg: "./file/32/14.webp",
    modelwearmob:"./file/32/20.avif",
    modelwearpc:"./file/32/20.avif",
    shortdesc: "This Oxford defines every suit with quiet authority",
    longdesc: "For those who value presence this Oxford defines every suit with quiet authority",
    model:"Designed Smooth Presence Guaranteed",
    modelimg:"./file/32/6.webp",
techdesc1:"For those who value presence this Oxford crafted from premium genuine leather defines success through quiet authority and timeless distinction .",
techdesc2:"Designed for leaders who move with confidence elevating every suit meeting and occasion with effortless refinement and command .",
    Upper:"Premium smooth full grain leather with a refined semi matte finish that offers supreme .",
    Inner:"100% natural breathable leather lining that absorbs moisture and prevents sweat or odors all day long .",
    Insole:"Cushioned genuine leather insole with high density foam for maximum shock absorption and orthopedic comfort .",
    Outsole:"Sleek lightweight premium rubber dress sole providing excellent flexibility slip resistance and a classic formal profile .",
    modelname:"Oxford",
    modeldesc:"Oxford Shoes Refined Elegance Everyday Sophistication Oxford shoes are more than just footwear they are a sleek polished choice The closed lacing profile gives you a secure fit that feels tailored all day They elevate everything from suits to smart casual looks with a classic edge that always stands out Refined stitching premium leathers and a sleek silhouette make them easy to rely on Elegant powerful and always on point Oxford shoes give you grace without overthinking it Oxford where formal grace meets modern wear",
title: " Vonaldo Capri Comfort Oxford Shoes for Men | Premium Genuine Leather Formal Elegance",
metadesc: "Discover Capri Comfort Oxford shoes crafted from premium genuine leather. Designed for quiet confidence and timeless distinction, offering refined comfort, breathable lining, and a sleek formal silhouette for suits, meetings, and elevated everyday wear.",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/32/14.webp",
          "./file/32/5.webp",
          "./file/32/12.webp",
          "./file/32/7.webp",
          "./file/32/4.webp",
          
          
        ],
        colorimg:"./file/32/200.webp",
        sizes: [
          { size: 5, id: 47729030791357 },
          { size: 6, id: 47729030758589 },
          { size: 7, id: 47729030856893 },
          { size: 8, id: 47729030824125 },
          { size: 9, id: 47729030529213 },
          { size: 10, id: 47729030496445 },
          { size: 11, id: 47729030594749 },
          { size: 12, id: 47729030561981 },
          { size: 13, id: 47729030660285 },
        ],
      },
    ],
  },
















 
 
   {
    id: 47729053925565,
    name: "Montero Monk",
    desc: "Crafted to Step Into Confidence",
    price: 169,
    oldprice: 230,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Natural Leather",
    mainimg: "./file/19/11.webp",
    modelwearmob:"./file/19/10.avif",
    modelwearpc:"./file/19/10.avif",
    shortdesc: "Monk strap shoe with refined structure and bold presence",
    longdesc: "Monk strap shoe with refined structure and minimal design for confident presence",
    model:"Refined Step Monk Edition",
    modelimg:"./file/19/15.webp",
techdesc1: "Confidence in every step. Crafted from genuine black leather and defined by a refined monk strap design this shoe is built for those who move seamlessly between polished formal looks and laid-back elevated outfits with effortless confidence.",

techdesc2: "Designed to project quiet confidence, it adds a distinctive touch of sophistication to your style while elevating your presence effortlessly.",
    Upper:"Premium smooth leather with a refined matte finish, featuring classic moc-toe stitching and a distinctive buckle strap for an elevated, structured look",
    Inner:"Soft natural leather lining for exceptional comfort, reduced friction, and enhanced breathability",
    Insole:"Anatomical leather footbed with a shock-absorbing layer, designed to support the foot and provide all-day comfort",
    Outsole:"Lightweight chunky platform sole with a textured finish, delivering strong grip, durability, and a bold modern edge without added weight",
    modelname:"Monk Strap",
    modeldesc:"Monk strap shoes are more than formal footwear, they're a refined confident statement crafted from premium materials with a secure buckle closure, clean lines, and a structured silhouette that moves effortlessly from business meetings to smart casual occasions, delivering everyday sophistication, lasting comfort, and a quiet presence that never tries too hard, because true style speaks for itself through every season and every step.",
title: "Vonaldo Montero Monk Strap Shoes for Men | Premium Leather Buckle Shoes – Modern Formal Style",

metadesc: "Shop Vonaldo Montero Monk Strap shoes for men made from premium natural leather with a refined buckle design, lightweight comfort sole, and all-day support. Perfect for business, formal occasions, and smart casual outfits with a confident modern look.",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/19/11.webp",
          "./file/19/15.webp",
          "./file/19/2.webp",
          "./file/19/7.webp",
          "./file/19/18.webp",
          "./file/19/3.webp",

        ],
        colorimg:"./file/19/110.webp",
        sizes: [
          { size: 6.5, id: 48223329452221 },
          { size: 7.5, id: 48223329419453 },
          { size: 8, id: 48223329517757 },
          { size: 8.5, id: 48223329484989 },
          { size: 9, id: 48223329583293 },
          { size: 9.5, id: 48223329550525 },
        ],
      },
    ],
  },
   {
    id: 47729075191997,
    name: "Torino Monk",
    desc: "Elegance Buckled in Motion",
    price: 219,
    oldprice: 290,
    vare:"Essential",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
material: "Premium Polished Natural Leather",
    mainimg: "./file/20/4.webp",
    modelwearmob:"./file/20/10.avif",
    modelwearpc:"./file/20/20.avif",
    shortdesc: "Leather monk strap with subtle sheen and refined modern style",
    longdesc: "Monk strap shoe in genuine leather with sheen and refined modern character",
    model:"Pure Comfort Monk",
    modelimg:"./file/20/4.webp",
    techdesc1:"Crafted for maximum impact this monk strap blends timeless structure with modern refinement delivering effortless comfort and a confident presence in every step.",
    techdesc2:"Where classic refinement meets urban edge this is a true standout piece designed to anchor your style with effortless confidence.",
    Upper:"polished leather with a smooth finish, featuring a sleek single buckle strap for a bold and timeless look",
    Inner:"Soft natural leather lining for exceptional comfort, reduced friction, and enhanced breathability",
    Insole:"Cushioned leather footbed with a shock-absorbing layer, designed to support your feet and provide all-day comfort",
    Outsole:"Lightweight chunky lug sole delivering strong grip, durability, and a bold modern style without added weight",
    modelname:"Monk Strap",
      modeldesc:"Monk strap shoes are more than formal footwear, they're a refined confident statement crafted from premium materials with a secure buckle closure, clean lines, and a structured silhouette that moves effortlessly from business meetings to smart casual occasions, delivering everyday sophistication, lasting comfort, and a quiet presence that never tries too hard, because true style speaks for itself through every season and every step.",
title: "Vonaldo Montero Monk Strap Shoes for Men | Premium Leather Buckle Shoes – Modern Formal Style",
title: "Vonaldo Torino Monk | Pure Comfort Buckle Shoes – Premium Leather & Modern Elegance",
metadesc: "Step into refined confidence with Torino Monk shoes. Crafted from premium natural leather with a cushioned insole and lightweight chunky sole, delivering pure comfort, modern elegance, and all-day sophistication in every step.",
    colors: [
      {
        color: "Black",
        imgs: [
"./file/20/4.webp",
"./file/20/14.webp",
"./file/20/1.webp",
"./file/20/13.webp",
"./file/20/6.webp",
"./file/20/9.webp",
"./file/20/16.webp",
        ],
        colorimg:"./file/20/160.webp",
        sizes: [
          { size: 6, id: 47729075191997 },
          { size: 6.5, id: 47729075224765 },
          { size: 7, id: 47729075323069 },
          { size: 7.5, id: 47729075355837 },
          { size: 8, id: 47729075257533 },
          { size: 8.5, id: 47729075290301 },
          { size: 9, id: 47729075454141 },
          { size: 9.5, id: 47729075486909 },
        ],
      },
    ],
  },

    {
    id: 47729104912573,
    name: "Vesper Chelsea",
    desc: "Every Step Hits Different",
    price: 179,
    oldprice: 240,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Genuine Leather",
    mainimg: "./file/8/7.webp",
    modelwearmob:"./file/8/10.avif",
    modelwearpc:"./file/8/40.avif",
    shortdesc: "Genuine leather Chelsea boot built for confident presence",
    longdesc: "Built to stand out Chelsea boot in genuine leather elevating with confidence",
    model:"Modern Grip Chelsea Boot",
    modelimg:"./file/8/1.webp",
techdesc1: "Black genuine leather Chelsea boot with chunky lug sole bold street presence refined all-day comfort and stylist-level craftsmanship for confident modern style.",

techdesc2: "Built for those who dress with intention this Chelsea boot commands presence the moment you walk in pairing bold street edge with the kind of comfort that carries you through the day without compromise.",
    Upper:"Premium smooth leather with a refined matte finish, paired with durable elastic side panels for flexibility and effortless wear",
    Inner:"Premium natural leather lining with breathable sections for enhanced comfort and all-day ventilation",
    Insole:"Cushioned anatomical footbed, leather-lined for superior comfort and excellent shock absorption",
    Outsole:"Lightweight yet durable chunky lug outsole with a slip-resistant design for strong grip, stability, and a bold modern look",
    modelname:"Chunky Chelsea Boots",
    modeldesc:"Chunky Chelsea Boots are more than just footwear they are a bold modern statement The sturdy silhouette and elastic side panels give you a secure comfortable fit that feels strong all day They work for everything from city walks to casual nights out with a rugged look that always stands out Simple details quality materials and a thick durable sole make them easy to rely on Comfortable versatile and always confident Chunky Chelsea Boots give you presence without overthinking it Chunky Chelsea where bold style meets everyday edge",
title: "Vonaldo Vesper Chelsea Boot | Chunky Grip Sole Premium Leather – Modern Urban Style & All-Day Comfort",
metadesc: "Discover Vesper Chelsea Boots by Vonaldo, crafted from premium natural leather with a bold chunky grip sole for superior stability, comfort, and durability. Designed for modern urban style, effortless versatility, and confident everyday wear",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/8/7.webp",
          "./file/8/10.webp",
          "./file/8/6.webp",
            "./file/8/5.webp",
          "./file/8/4.webp",
          "./file/8/3.webp",
          "./file/8/1.webp",
        ],
        colorimg:"./file/8/70.webp",
        sizes: [
          { size: 6, id: 47729104912573 },
          { size: 6.5, id: 47729104847037 },
          { size: 7.5, id: 47729104879805 },
          { size: 8, id: 47729104552125 },
          { size: 8.5, id: 47729104584893 },
          { size: 9, id: 47729104486589 },
          { size: 9.5, id: 47729104519357 },
        ],
      },
    ],
  },
  {
    id: 47729127489725,
    name: "Capri Soul",
    desc: "Clean Style Natural Comfort",
    price: 169,
    oldprice: 230,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Genuine  Leather",
    mainimg: "./file/9/4.webp",
    modelwearmob:"./file/9/20.avif",
    modelwearpc:"./file/9/20.avif",
    shortdesc: "Refined Minimal Genuine  Leather with Lightweight Comfort",
    longdesc: "Refined Minimal Genuine  Leather with Lightweight Comfort and Effortless Style",
    model:"Refined Comfort Leather Boot",
    modelimg:"./file/9/8.webp",
    techdesc1:"Crafted from genuine leather, this Chelsea boot blends a refined modern silhouette with lightweight comfort — built for the man who carries quiet confidence wherever the day takes him, from boardrooms to city streets after dark.",
    techdesc2:"Every step feels like it was made for you. Effortlessly comfortable and distinctly refined this shoe is light enough to forget and memorable enough to leave an impression.",
    Upper:"Premium smooth leather with a clean refined finish and elastic side panels for effortless slip-on comfort",
    Inner:"Breathable leather lining that molds naturally to your foot for lasting comfort",
    Insole:"Cushioned leather insole delivering soft support and impact absorption",
    Outsole:"Lightweight EVA chunky sole designed for grip, stability, and a modern minimal look",
    modelname:"Chelsea Boot",
    modeldesc:"Chelsea Boots Effortless Edge Everyday Confidence Chelsea boots are more than just footwear they are a sleek confident choice The slip-on design and elastic panels give you a comfortable fit that feels natural all day They work for everything from work to casual outings with a seamless look that always fits in Minimalist details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Chelsea boots give you style without overthinking it Chelsea where modern edge meets everyday wear",
title: "Vonaldo Capri Soul Chelsea Boot | Premium Leather Minimal Design – Lightweight Comfort",

metadesc: "Step into effortless style with Vonaldo Capri Soul Chelsea Boot. Crafted from premium natural leather with a lightweight EVA sole, delivering all-day comfort, clean minimal design, and refined modern elegance",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/9/4.webp",
          "./file/9/7.webp",
          "./file/9/6.webp",
          "./file/9/50.webp",
          "./file/9/1.webp",
          "./file/9/3.webp",


        ],
        colorimg:"./file/9/20.webp",
        sizes: [
          { size: 6, id: 47729127489725 },
          { size: 6.5, id: 47729127260349 },
          { size: 7.5, id: 47729127227581 },
          { size: 8, id: 47729127194813 },
          { size: 8.5, id: 47729127162045 },
          { size: 9, id: 47729127325885 },
          { size: 9.5, id: 47729127293117 },
        ],
      },
    ],
  },

  {
    id: 47729144398013,
    name: "Modern Heritage",
    desc: "Refined for Real Life",
    price: 190,
    oldprice: 260,
    vare:"Essential",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Natural Leather",
    mainimg: "./file/11/6.webp",
     modelwearmob:"./file/11/10.avif",
    modelwearpc:"./file/11/10.avif",
    shortdesc: "Elevated Chelsea boot refined leather effortless comfort",
    longdesc: "Elevated Chelsea boot with refined leather finish and effortless comfort",
    model:"Bold Comfort Everyday Essential",
    modelimg:"./file/11/2.webp",
    techdesc1:"Crafted from premium genuine black leather with a bold chunky sole this Chelsea boot combines effortless modern style with lasting all-day comfort and a confident grip in every step.",
    techdesc2:"Slip on Step out The Chelsea silhouette does the rest versatile enough for the boardroom effortless enough for the weekend.",
Upper: "Premium full grain leather engineered with a smooth polished finish and natural durability",
Inner: "Breathable genuine leather lining designed for premium moisture control and optimal foot comfort",
Insole: "Ergonomic high rebound cushioned footbed providing advanced shock absorption and all day support",
Outsole: "Lightweight chunky rubber outsole delivering superior anti slip traction and a modern profile",
    modelname:"Chunky Chelsea Boots",
    modeldesc:"Chunky Chelsea Boots are more than just footwear they are a bold modern statement The sturdy silhouette and elastic side panels give you a secure comfortable fit that feels strong all day They work for everything from city walks to casual nights out with a rugged look that always stands out Simple details quality materials and a thick durable sole make them easy to rely on Comfortable versatile and always confident Chunky Chelsea Boots give you presence without overthinking it Chunky Chelsea where bold style meets everyday edge",
title: "Vonaldo Modern Heritage Chelsea Boots – Premium Natural Leather Chunky Boots for Everyday Comfort",

metadesc: "Step into timeless sophistication with Vonaldo Modern Heritage Chelsea Boots. Crafted from premium natural leather and finished with a bold chunky sole, delivering modern style, lasting comfort, and effortless versatility.",

    colors: [
      {
        color: "Black",
        imgs: [
          "./file/11/6.webp",
          "./file/11/4.webp",
          "./file/11/8.webp",
          "./file/11/5.webp",
          "./file/11/10.webp",
          "./file/11/7.webp",
        ],
        colorimg:"./file/11/60.webp",
        sizes: [
          { size: 6, id: 47729144398013 },
          { size: 6.5, id: 47729144823997 },
          { size: 7.5, id: 47729144791229 },
          { size: 8, id: 47729144758461 },
          { size: 8.5, id: 47729144725693 },
          { size: 9, id: 47729144692925 },
          { size: 9.5, id: 47729144660157 },
        ],
      },
    ],
  },
     {
    id: 47729241555133,
    name: "Lucento",
    desc: "Made to Own Attention",
    price: 189,
    oldprice: 255,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium glossy Leather",
    mainimg: "./file/12/1.webp",
    modelwearmob:"./file/12/20.avif",
    modelwearpc:"./file/12/20.avif",
    shortdesc: "Chelsea boot effortlessly stylish with modern edge and attitude",
    longdesc: "Effortlessly stylish Chelsea boot with modern edge and attitude every step",
    model:"Italian Leather Chelsea",
    modelimg:"./file/12/5.webp",
        techdesc1:"Lucento gives you a standout presence with lightweight comfort that keeps every step confident from day to night.",
    techdesc2:"Built for casual days and sharp nights, offering confident grip, lasting comfort, and a modern edge that stands out.",
Upper: "Premium high gloss patent leather engineered with a mirror finish shine and superior durability",
Inner: "Breathable ultra soft lining designed for optimal moisture control and absolute foot comfort",
Insole: "Ergonomic cushioned footbed providing advanced shock absorption and all day structural support",
Outsole: "Lightweight chunky rubber lug sole delivering superior anti slip traction and a bold modern profile",
    modelname:"Chunky Chelsea Boots",
    modeldesc:"Chunky Chelsea Boots are more than just footwear they are a bold modern statement The sturdy silhouette and elastic side panels give you a secure comfortable fit that feels strong all day They work for everything from city walks to casual nights out with a rugged look that always stands out Simple details quality materials and a thick durable sole make them easy to rely on Comfortable versatile and always confident Chunky Chelsea Boots give you presence without overthinking it Chunky Chelsea where bold style meets everyday edge",
title: "Vonaldo Lucento – Statement Combat Boots Built for Modern Confidence",
metadesc: "Designed to stand out, Lucento combat boots deliver bold shine, secure traction, and effortless comfort for powerful day-to-night styling",

    colors: [
      {
        color: "Black",
        imgs: [
"./file/12/1.webp",
"./file/12/7.webp",
"./file/12/4.webp",
"./file/12/3.webp",
"./file/12/5.webp",
"./file/12/2.webp",

        ],
        colorimg:"./file/12/10.webp",
        sizes: [
          { size: 6.5, id: 48222116741309 },
          { size: 7.5, id: 48222116774077 },
          { size: 8, id: 48222116806845 },
          { size: 8.5, id: 48222116839613 },
          { size: 9, id: 48222116872381 },
          { size: 9.5, id: 48222116905149 },
          { size: 10.5, id: 48222116937917 },
        ],
      },
    ],
  },

  {
    id: 47729253122237,
    name: "Monte Nero",
    desc: "Soft steps , loud presence",
    price: 180,
    oldprice: 240,
    vare:"New Collection",
     sizeguide:"./icons/main.webp",
     listcolor:"#f5f3ef",
    material:"Premium Suede Leather",
    mainimg: "./file/13/9.webp",
    modelwearmob:"./file/13/50.avif",
    modelwearpc:"./file/13/40.avif",
    shortdesc: "Soft landing, fluid comfort, so light you forget you're wearing it",
    longdesc: "Soft landing fluid comfort with design, so light you forget you're wearing it",
    model:"Effortless all-day refined comfort",
    modelimg:"./file/13/9.webp",
    techdesc1:"Lightweight by design, effortless by nature delivering soft, fluid comfort that feels barely there and keeps every step perfectly smooth.",
    techdesc2:"From morning errands to evening plans, this silhouette adapts effortlessly cushioned by a comfortable sole that keeps every step light and easy.",
    Upper:"Crafted from premium Italian suede leather featuring a rich, velvety texture and clean minimal stitching for a sleek editorial aesthetic",
    Inner:"Lined with ultra-soft, breathable genuine natural leather to provide a flawless glove-like fit and all-day climate control",
    Insole:"Anatomically engineered, high-density cushioned foam covered in smooth leather for advanced shock absorption and personalized support",
    Outsole:"Durable tonal rubber cupsole with a modern chunky silhouette, reinforced by a secure 360° perimeter stitch for long-lasting wear",
    modelname:"Hybrid Chelsea Sneaker",
    modeldesc: " Monte Nero Hybrid Chelsea Sneakers are more than just footwear they are a sleek modern statement The refined silhouette and elastic side panels give you a plush comfortable fit that feels effortless all day They work for everything from morning meetings to upscale nights out with a clean look that always stands out Minimal details premium materials and a smart sneaker sole make them easy to rely on Sophisticated versatile and always polished Hybrid Chelsea Sneakers give you distinction without overthinking it Hybrid Chelsea where luxury comfort meets modern design",
title: "Vonaldo Monte Nero Chelsea Sneaker – Premium Suede Lightweight Comfort Shoes.",

metadesc: "Discover Vonaldo Hybrid Chelsea Sneakers crafted from premium suede leather with lightweight all-day comfort, cushioned support, and a versatile modern design that fits both casual and smart looks.",

    colors: [
      {
        color: "Black",
        imgs: [
"./file/13/9.webp",
"./file/13/10.webp",
"./file/13/1.webp",
"./file/13/25.webp",
"./file/13/5.webp",
"./file/13/66.webp",


        ],
        colorimg:"./file/13/90.webp",
        sizes: [
          { size: 6, id: 47729253122237 },
          { size: 6.5, id: 47729253089469 },
          { size: 7.5, id: 47729252925629 },
          { size: 8, id: 47729252892861 },
          { size: 8.5, id: 47729252860093 },
          { size: 9, id: 47729252827325 },
          { size: 9.5, id: 47729253056701 },
        ],
      },
      {
        color: "Beige",
        imgs: [
"./file/14/4.webp",
"./file/14/11.webp",
"./file/14/9.webp",
"./file/14/5.webp",
"./file/14/7.webp",
"./file/14/8.webp",
        ],
        colorimg:"./file/14/40.webp",
        sizes: [
          { size: 6, id: 47729253023933 },
          { size: 6.5, id: 47729252991165 },
          { size: 7.5, id: 47729252958397 },
          { size: 8, id: 47729252597949 },
          { size: 8.5, id: 47729252565181 },
          { size: 9, id: 47729252532413 },
          { size: 9.5, id: 47729252499645 },
        ],
      },
    ],
  },

  {
    id: 47729278058685,
    name: "Como Heritage",
    desc: "Old soul, new sole, timeless story",
    price: 220,
    oldprice: 290,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Suede Leather",
    mainimg: "./file/15/8.avif",
    shortdesc: "Western attitude, modern suede Chelsea boot inspired by classic",
    longdesc: "Western attitude Modern suede Chelsea boot inspired by classic western style",
    model:"Premium Feel Everyday Ease",
    modelimg:"./file/15/8.avif",
            modelwearmob:"./file/15/50.avif",
    modelwearpc:"./file/15/100.avif",
    techdesc1:"Western attitude, modern comfort. A suede Chelsea boot inspired by classic western style and designed for confident everyday wear.",
    techdesc2:"Slip it on once and you'll never want to take it off comfort that lasts all day every day.",
    Upper:"Premium suede upper with a soft feel and a clean structured look that adds effortless style to any outfit.",
    Inner:"Comfortable inner lining designed to give a smooth feel and support for long hours of wear.",
    Insole:"Cushioned insole built for lasting comfort and better everyday support with every step.",
    Outsole:"Durable chunky outsole with strong grip and stability, giving confident movement across different surfaces.",
    modelname:"Chelsea",
    modeldesc:"Chelsea Boots Effortless Edge Everyday Confidence Chelsea boots are more than just footwear they are a sleek confident choice The slip-on design and elastic panels give you a comfortable fit that feels natural all day They work for everything from work to casual outings with a seamless look that always fits in Minimalist details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Chelsea boots give you style without overthinking it Chelsea where modern edge meets everyday wear",
    title:"Vonaldo Como Heritage Chelsea Boots | Premium Suede Leather with Modern Comfort",
    metadesc:"Designed for confident everyday wear, these premium suede Chelsea boots combine lasting comfort, a sleek slip-on fit, and a refined modern look that elevates any outfit.",
    colors: [
      {
        color: "Khaki",
        imgs: [
"./file/15/8.avif",
"./file/15/7.avif",
"./file/15/2000.avif",
"./file/15/10.avif",
"./file/15/5.avif",
"./file/15/160.avif",


        ],
        colorimg:"./file/15/8.avif",
        sizes: [
          { size: 6, id: 47729278058685 },
          { size: 6.5, id: 47729277894845 },
          { size: 7.5, id: 47729277862077 },
          { size: 8, id: 47729277960381 },
          { size: 8.5, id: 47729277927613 },
          { size: 9, id: 47729277829309 },
        ],
      },
      {
        color: "Black",
        imgs: [
"./file/16/14.avif",
"./file/16/5.avif",
"./file/16/1.avif",
"./file/16/7.avif",
"./file/16/9.avif",
"./file/16/13.avif",

        ],
        colorimg:"./file/16/8.avif",
        sizes: [
          { size: 6, id: 47729277796541 },
          { size: 6.5, id: 47729278288061 },
          { size: 7.5, id: 47729278255293 },
          { size: 8, id: 47729278353597 },
          { size: 8.5, id: 47729278320829 },
          { size: 9, id: 47729278156989 },
        ],
      },
    ],
  },
  {
    id: 47729293983933,
    name: "Stoneford",
    desc: "Calm confidence, every step",
    price: 170,
    oldprice: 230,
    vare:"Essential",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Suede Leather",
    mainimg: "./file/17/6.webp",
    shortdesc: "Soft above unshaken below this Chelsea boot built to last",
    longdesc: "Soft above unshaken below this Chelsea moves with confidence built to last",
    model:"Premium Suede Chelsea",
    modelimg:"./file/17/2.webp",
    modelwearmob:"./file/17/70.avif",
    modelwearpc:"./file/17/40.avif",
    techdesc1:"Black suede with a soft brushed finish that shifts under light, revealing subtle depth. Smooth and structured, with a confident magnetic presence from formal to everyday wear.",
    techdesc2:"Some shoes you wear. This one walks with you — soft suede solid ground and confident in every move wherever the day takes you.",
    Upper:"Crafted from premium Premium suede leather that features a rich velvet texture and deep jet-black finish for a luxurious look and feel.",
    Inner:"Lined with ultra-soft natural leather to provide maximum breathability and a smooth feel against the foot ensuring all-day comfort.",
    Insole:"Features a high-density cushioned leather insole that molds perfectly to your foot anatomy offering exceptional support and shock absorption.",
    Outsole:"Engineered with a durable yet surprisingly lightweight rubber lug sole designed with deep treads to deliver superior anti-slip traction and a bold modern silhouette.",
    modelname:"Chelsea",
    modeldesc:"Chelsea Boots Effortless Edge Everyday Confidence Chelsea boots are more than just footwear they are a sleek confident choice The slip-on design and elastic panels give you a comfortable fit that feels natural all day They work for everything from work to casual outings with a seamless look that always fits in Minimalist details quality materials and a sharp silhouette make them easy to rely on Comfortable versatile and always on point Chelsea boots give you style without overthinking it Chelsea where modern edge meets everyday wear",
title: "Vonaldo Stoneford Chelsea Boots – Refined Premium Suede with Modern Confidence.",

metadesc: "Elevate your everyday style with Vonaldo Stoneford Chelsea Boots, featuring premium Italian suede leather, lightweight comfort, and a sleek modern silhouette built for versatile wear.",
    colors: [
      {
        color: "Black",
        imgs: [
"./file/17/6.webp",
"./file/17/8.webp",
"./file/17/11.webp",
"./file/17/5.webp",
"./file/17/12.webp",
        ],
        colorimg:"./file/17/10.webp",
        sizes: [
          { size: 6.5, id: 47729293983933 },
          { size: 7.5, id: 47729293918397 },
          { size: 8, id: 47729293689021 },
          { size: 8.5, id: 47729293656253 },
          { size: 9, id: 47729293754557 },
          { size: 9.5, id: 47729293721789 },
        ],
      },
    ],
  },

     
  {
    id: 8080,
    name: "Sereno",
    desc: "Less noise, more presence",
    price: 159,
    oldprice: 210,
    vare:"Essential",
    sizeguide:"./file/26/50.avif",
    listcolor:"#f5f3ef",
    material:"Premium Suede Leather",
    mainimg: "./file/26/20.avif",
    modelwearmob:"./file/26/2.avif",
    modelwearpc:"./file/26/2.avif",
    shortdesc: "Penny loafer built for timeless comfort, made to stay unnoticed",
    longdesc: "Penny loafer built for comfort that never goes out of style, made to stay unnoticed",
    model:"Italian Penny Loafer",
    modelimg:"./file/26/15.avif",
    techdesc1:"Soft suede shaped into a penny loafer that feels like it's always been yours, made for the days you don't want to think twice.",
    techdesc2:"Lightweight comfort, breathable leather lining, and a versatile neutral tone make it perfect for refined everyday smart casual wear.",
Upper:"Premium suede leather with refined moc-toe stitching that highlights craftsmanship and clean timeless design",

Inner:"Full natural leather lining offering breathability softness and all-day comfort for effortless wear",

Insole:"Cushioned leather insole designed for gentle support pressure absorption and premium walking comfort",

Outsole:"Lightweight flexible rubber sole inspired by classic driving shoes delivering grip comfort and easy movement",
    modelname:"Penny Loafer",
modeldesc:"Penny Loafers are not just footwear they are a symbol of timeless identity The refined silhouette with signature penny strap detail delivers quiet confidence and effortless elegance in every step They transition seamlessly from tailored office looks to relaxed modern wear maintaining a clean understated presence Premium suede and leather craftsmanship combined with a flexible sole create everyday comfort with a luxury feel Sophisticated versatile and always refined Penny Loafers embody effortless distinction without excess Penny Loafers where heritage craftsmanship meets modern quiet luxury",
            title:"Vonaldo Sereno Taupe Penny Loafer – Timeless Suede Design with Modern Elegance",
    metadesc:"Step into refined style with Sereno Taupe Penny Loafer featuring premium suede Italian craftsmanship lightweight comfort and breathable leather lining Built for everyday smart casual wear with a clean neutral tone and effortless modern luxury",
    colors: [
      {
        color: "Taupe",
        imgs: [
"./file/26/20.avif",
"./file/26/15.avif",
"./file/26/7.avif",
"./file/26/13.avif",
"./file/26/27.avif",
"./file/26/21.avif",
"./file/26/24.avif",
        ],
        colorimg:"./file/26/200.avif",
        sizes: [
          { size: 6, id: 47729348247741 },
          { size: 6.5, id: 47729348214973 },
          { size: 7, id: 47729348116669 },
          { size: 8, id: 47729348083901 },
          { size: 8.5, id: 47729348182205 },
          { size: 9.5, id: 47729348149437 },
          { size: 10, id: 47729347985597 },
          { size: 11, id: 47729347952829 },
          { size: 12, id: 47729348051133 },
        ],
      },
      {
        color: "Navy",
        imgs: [
"./file/27/10.avif",
"./file/27/1.avif",
"./file/27/7.avif",
"./file/27/8.avif",
        ],
        colorimg:"./file/27/3.avif",
        sizes: [
          { size: 6, id: 47729348018365 },
          { size: 6.5, id: 47729347854525 },
          { size: 7, id: 47729347821757 },
          { size: 8, id: 47729347920061 },
          { size: 8.5, id: 47729347887293 },
          { size: 9.5, id: 47729347723453 },
          { size: 10, id: 47729347690685 },
          { size: 11, id: 47729347788989 },
          { size: 12, id: 47729347756221 },
        ],
      },
      {
        color: "Stone",
        imgs: [
"./file/28/9.avif",
"./file/28/100.avif",
"./file/28/5.avif",
"./file/28/160.avif",
"./file/28/7.avif",
"./file/28/13.avif",
        ],
        colorimg:"./file/28/90.avif",
        sizes: [
          { size: 6, id: 47729347592381 },
          { size: 6.5, id: 47729347559613 },
          { size: 7, id: 47729347657917 },
          { size: 8, id: 47729347625149 },
          { size: 8.5, id: 47729347461309 },
          { size: 9.5, id: 47729347428541 },
          { size: 10, id: 47729347526845 },
          { size: 11, id: 47729347494077 },
          { size: 12, id: 47729347395773 },
        ],
      },
    ],
  },
  {
    id: 8090,
    name: "Sereno Navy",
    desc: "Less noise, more presence",
    price: 159,
    oldprice: 210,
    vare:"Essential",
    sizeguide:"./file/26/50.avif",
    listcolor:"#f5f3ef",
    material:"Premium Suede Leather",
    mainimg: "./file/27/10.avif",
    modelwearmob:"./file/27/40.avif",
    modelwearpc:"./file/27/30.avif",
    shortdesc: "Penny loafer built for timeless comfort, made to stay unnoticed",
    longdesc: "Penny loafer built for comfort that never goes out of style, made to stay unnoticed",
        model:"Italian Penny Loafer",
            modelimg:"./file/27/1.avif",
    techdesc1:"Soft suede shaped into a penny loafer that feels like it's always been yours, made for the days you don't want to think twice.",
    techdesc2:"Lightweight comfort, breathable leather lining, and a versatile neutral tone make it perfect for refined everyday smart casual wear.",
Upper:"Premium suede leather with refined moc-toe stitching that highlights craftsmanship and clean timeless design",

Inner:"Full natural leather lining offering breathability softness and all-day comfort for effortless wear",

Insole:"Cushioned leather insole designed for gentle support pressure absorption and premium walking comfort",

Outsole:"Lightweight flexible rubber sole inspired by classic driving shoes delivering grip comfort and easy movement",
    modelname:"Penny Loafer",
modeldesc:"Penny Loafers are not just footwear they are a symbol of timeless identity The refined silhouette with signature penny strap detail delivers quiet confidence and effortless elegance in every step They transition seamlessly from tailored office looks to relaxed modern wear maintaining a clean understated presence Premium suede and leather craftsmanship combined with a flexible sole create everyday comfort with a luxury feel Sophisticated versatile and always refined Penny Loafers embody effortless distinction without excess Penny Loafers where heritage craftsmanship meets modern quiet luxury",
            title:"Vonaldo Sereno Navy Penny Loafer – Timeless Suede Design with Modern Quiet Luxury Style",
    metadesc:"Step into refined simplicity with Sereno Navy Penny Loafer featuring premium suede Italian craftsmanship and lightweight comfort Designed for everyday elegance smart casual wear and effortless modern style that defines quiet luxury",
    colors: [
      {
        color: "Navy",
        imgs: [
"./file/27/10.avif",
"./file/27/1.avif",
"./file/27/7.avif",
"./file/27/8.avif",

        ],
        colorimg:"./file/27/3.avif",
        sizes: [
          { size: 6, id: 47729348018365 },
          { size: 6.5, id: 47729347854525 },
          { size: 7, id: 47729347821757 },
          { size: 8, id: 47729347920061 },
          { size: 8.5, id: 47729347887293 },
          { size: 9.5, id: 47729347723453 },
          { size: 10, id: 47729347690685 },
          { size: 11, id: 47729347788989 },
          { size: 12, id: 47729347756221 },
        ],
      },
      {
        color: "Taupe",
        imgs: [
"./file/26/20.avif",
"./file/26/15.avif",
"./file/26/7.avif",
"./file/26/13.avif",
"./file/26/27.avif",
"./file/26/21.avif",
"./file/26/24.avif",
        ],
        colorimg:"./file/26/200.avif",
        sizes: [
          { size: 6, id: 47729348247741 },
          { size: 6.5, id: 47729348214973 },
          { size: 7, id: 47729348116669 },
          { size: 8, id: 47729348083901 },
          { size: 8.5, id: 47729348182205 },
          { size: 9.5, id: 47729348149437 },
          { size: 10, id: 47729347985597 },
          { size: 11, id: 47729347952829 },
          { size: 12, id: 47729348051133 },
        ],
      },
      {
        color: "Stone",
        imgs: [
"./file/28/9.avif",
"./file/28/100.avif",
"./file/28/5.avif",
"./file/28/160.avif",
"./file/28/7.avif",
"./file/28/13.avif",
        ],
        colorimg:"./file/28/90.avif",
        sizes: [
          { size: 6, id: 47729347592381 },
          { size: 6.5, id: 47729347559613 },
          { size: 7, id: 47729347657917 },
          { size: 8, id: 47729347625149 },
          { size: 8.5, id: 47729347461309 },
          { size: 9.5, id: 47729347428541 },
          { size: 10, id: 47729347526845 },
          { size: 11, id: 47729347494077 },
          { size: 12, id: 47729347395773 },
        ],
      },
    ],
  },
  {
    id: 80100,
    name: "Sereno Stone",
    desc: "Less noise, more presence",
    price: 159,
    oldprice: 210,
    vare:"Essential",
    sizeguide:"./file/26/50.avif",
    listcolor:"#f5f3ef",
    material:"Premium Suede Leather",
    mainimg: "./file/28/9.avif",
    modelwearmob:"./file/28/20.avif",
    modelwearpc:"./file/28/10.avif",
    shortdesc: "Penny loafer built for timeless comfort, made to stay unnoticed",
    longdesc: "Penny loafer built for comfort that never goes out of style, made to stay unnoticed",
    model:"Italian Penny Loafer",
    modelimg:"./file/28/8.avif",
    techdesc1:"Soft suede shaped into a penny loafer that feels like it's always been yours, made for the days you don't want to think twice.",
    techdesc2:"Lightweight comfort, breathable leather lining, and a versatile neutral tone make it perfect for refined everyday smart casual wear.",
Upper:"Premium suede leather with refined moc-toe stitching that highlights craftsmanship and clean timeless design",
Inner:"Full natural leather lining offering breathability softness and all-day comfort for effortless wear",
Insole:"Cushioned leather insole designed for gentle support pressure absorption and premium walking comfort",
Outsole:"Lightweight flexible rubber sole inspired by classic driving shoes delivering grip comfort and easy movement",
  modelname:"Penny Loafer",
modeldesc:"Penny Loafers are not just footwear they are a symbol of timeless identity The refined silhouette with signature penny strap detail delivers quiet confidence and effortless elegance in every step They transition seamlessly from tailored office looks to relaxed modern wear maintaining a clean understated presence Premium suede and leather craftsmanship combined with a flexible sole create everyday comfort with a luxury feel Sophisticated versatile and always refined Penny Loafers embody effortless distinction without excess Penny Loafers where heritage craftsmanship meets modern quiet luxury",
            title:"Vonaldo Sereno Stone Penny Loafer – Timeless Suede Elegance with Modern Luxury Design",
    metadesc:"Step into refined elegance with Sereno Stone Penny Loafer featuring premium suede Italian craftsmanship lightweight comfort and breathable leather lining Built for everyday smart casual wear with a clean neutral tone and effortless modern sophistication",
    colors: [
      {
        color: "Stone",
        imgs: [
"./file/28/9.avif",
"./file/28/100.avif",
"./file/28/5.avif",
"./file/28/160.avif",
"./file/28/7.avif",
"./file/28/13.avif",
        ],
        colorimg:"./file/28/90.avif",
        sizes: [
          { size: 6, id: 47729347592381 },
          { size: 6.5, id: 47729347559613 },
          { size: 7, id: 47729347657917 },
          { size: 8, id: 47729347625149 },
          { size: 8.5, id: 47729347461309 },
          { size: 9.5, id: 47729347428541 },
          { size: 10, id: 47729347526845 },
          { size: 11, id: 47729347494077 },
          { size: 12, id: 47729347395773 },
        ],
      },
      {
        color: "Navy",
        imgs: [
"./file/27/10.avif",
"./file/27/1.avif",
"./file/27/7.avif",
"./file/27/8.avif",
        ],
        colorimg:"./file/27/3.avif",
        sizes: [
          { size: 6, id: 47729348018365 },
          { size: 6.5, id: 47729347854525 },
          { size: 7, id: 47729347821757 },
          { size: 8, id: 47729347920061 },
          { size: 8.5, id: 47729347887293 },
          { size: 9.5, id: 47729347723453 },
          { size: 10, id: 47729347690685 },
          { size: 11, id: 47729347788989 },
          { size: 12, id: 47729347756221 },
        ],
      },
      {
        color: "Taupe",
        imgs: [
"./file/26/20.avif",
"./file/26/15.avif",
"./file/26/7.avif",
"./file/26/13.avif",
"./file/26/27.avif",
"./file/26/21.avif",
"./file/26/24.avif",
        ],
        colorimg:"./file/26/200.avif",
        sizes: [
          { size: 6, id: 47729348247741 },
          { size: 6.5, id: 47729348214973 },
          { size: 7, id: 47729348116669 },
          { size: 8, id: 47729348083901 },
          { size: 8.5, id: 47729348182205 },
          { size: 9.5, id: 47729348149437 },
          { size: 10, id: 47729347985597 },
          { size: 11, id: 47729347952829 },
          { size: 12, id: 47729348051133 },
        ],
      },
    ],
  },
  {
    id: 5050,
    name: `Velluto`,
    desc: "The essence of fine craftsmanship",
    price: 179,
    oldprice: 240,
    vare:"Essential",
    sizeguide:"./file/29/50.avif",
    listcolor:"#f8f5f0",
    material:"Premium Suede Leather",
    mainimg: "./file/29/3.avif",
    modelwearmob:"./file/29/20.avif",
    modelwearpc:"./file/29/10.avif",
    shortdesc: "Two styles. One loafer. Made to turn every look into a statement",
    longdesc: "Two styles. One loafer. Made to turn every look into a statement",
    model:"Italian Suede Loafer",
    modelimg:"./file/29/9.avif",
techdesc1:"Premium Italian suede hand-finished into a timeless tassel loafer silhouette a quiet statement of artisanal craftsmanship made for those who notice the details.",

techdesc2:"Lightweight comfort meets a breathable leather lining designed to carry you seamlessly from smart-casual days to refined evening occasions.",

Upper: "Crafted from premium, ultra-soft suede leather, featuring meticulous moc-toe stitching and a classic tassel accent that deliver a luxurious texture and a refined, elegant silhouette.",
Inner: "Fully lined with supple, breathable genuine leather that gently wraps the foot, naturally regulating temperature, reducing friction, and ensuring maximum comfort even during sockless wear.",
Insole: "Ergonomically designed genuine leather footbed with premium built-in cushioning, engineered to absorb everyday shock and provide superior support for all-day comfort.",
Outsole: "Constructed from highly flexible, ultra-lightweight rubber with a durable, anti-slip profile, offering effortless movement, agility, and a smooth, comfortable stride.",
modelname:"Tassel Loafer",
modeldesc:"Tassel Loafers are not just footwear they are a symbol of refined tradition The elegant silhouette with signature tassel detail delivers timeless sophistication and effortless confidence in every step They transition seamlessly from formal occasions to relaxed smart casual settings maintaining a polished distinguished presence Premium suede and leather craftsmanship combined with a flexible sole create everyday comfort with a luxury feel Sophisticated versatile and always timeless Tassel Loafers embody classic elegance without excess Tassel Loafers where heritage style meets enduring refinement",
title:"Vonaldo Velluto Tassel Loafer – Italian Suede Craftsmanship & Refined Luxury Style",

metadesc:"Experience understated luxury with the Vonaldo Velluto Tassel Loafer. Crafted from premium Italian suede with exceptional comfort, flexible construction, and timeless elegance for modern smart-casual and formal wear.",
    colors: [
      {
        color: "Slate",
        imgs: [
"./file/29/3.avif",
"./file/29/8.avif",
"./file/29/14.avif",
"./file/29/9.avif",


        ],
        colorimg:"./file/29/30.avif",
        sizes: [
          { size: 6.5, id: 47729383637181 },
          { size: 7, id: 47729383604413 },
          { size: 8, id: 47729383571645 },
          { size: 8.5, id: 47729383538877 },
          { size: 9.5, id: 47729383506109 },
          { size: 10, id: 47729383801021 },
          { size: 11, id: 47729383768253 },
        ],
      },
            {
        color: "Cognac",
        imgs: [
"./file/30/2.avif",
"./file/30/11.avif",
"./file/30/3.avif",
"./file/30/5.avif",


        ],
        colorimg:"./file/30/20.avif",
        sizes: [
          { size: 6.5, id: 47729383276733 },
          { size: 7, id: 47729383243965 },
          { size: 8, id: 47729383211197 },
          { size: 8.5, id: 47729383178429 },
          { size: 9.5, id: 47729383735485 },
          { size: 10, id: 47729383702717 },
          { size: 11, id: 47729383669949 },
        ],
      },
            {
        color: "Brown",
        imgs: [
"./file/31/3.avif",
"./file/31/1.avif",
"./file/31/11.avif",
"./file/31/8.avif",


        ],
        colorimg:"./file/31/30.avif",
        sizes: [
          { size: 6.5, id: 47729382981821 },
          { size: 7, id: 47729382949053 },
          { size: 8, id: 47729382916285 },
          { size: 8.5, id: 47729383407805 },
          { size: 9.5, id: 47729383375037 },
          { size: 10, id: 47729383342269 },
          { size: 11, id: 47729383309501 },
        ],
      },
    ],
  },
  {
    id: 2000,
    name: "Velluto Cognac",
    desc: "The essence of fine craftsmanship",
    price: 179,
    oldprice: 240,
    vare:"Essential",
    sizeguide:"./file/29/50.avif",
    listcolor:"#f8f5f0",
    material:"Premium Suede Leather",
    mainimg: "./file/30/2.avif",
    modelwearmob:"./file/30/50.avif",
    modelwearpc:"./file/30/10.avif",
    shortdesc: "Two styles. One loafer. Made to turn every look into a statement",
    longdesc: "Two styles. One loafer. Made to turn every look into a statement",
    model:"Italian Suede Loafer",
    modelimg:"./file/30/2.avif",
techdesc1:"Premium Italian suede hand-finished into a timeless tassel loafer silhouette a quiet statement of artisanal craftsmanship made for those who notice the details.",

techdesc2:"Lightweight comfort meets a breathable leather lining designed to carry you seamlessly from smart-casual days to refined evening occasions.",

Upper: "Crafted from premium, ultra-soft suede leather, featuring meticulous moc-toe stitching and a classic tassel accent that deliver a luxurious texture and a refined, elegant silhouette.",
Inner: "Fully lined with supple, breathable genuine leather that gently wraps the foot, naturally regulating temperature, reducing friction, and ensuring maximum comfort even during sockless wear.",
Insole: "Ergonomically designed genuine leather footbed with premium built-in cushioning, engineered to absorb everyday shock and provide superior support for all-day comfort.",
Outsole: "Constructed from highly flexible, ultra-lightweight rubber with a durable, anti-slip profile, offering effortless movement, agility, and a smooth, comfortable stride.",
modelname:"Tassel Loafer",
modeldesc:"Tassel Loafers are not just footwear they are a symbol of refined tradition The elegant silhouette with signature tassel detail delivers timeless sophistication and effortless confidence in every step They transition seamlessly from formal occasions to relaxed smart casual settings maintaining a polished distinguished presence Premium suede and leather craftsmanship combined with a flexible sole create everyday comfort with a luxury feel Sophisticated versatile and always timeless Tassel Loafers embody classic elegance without excess Tassel Loafers where heritage style meets enduring refinement",
title:"Vonaldo Velluto Tassel Loafer – Italian Suede Craftsmanship & Refined Luxury Style",

metadesc:"Experience understated luxury with the Vonaldo Velluto Tassel Loafer. Crafted from premium Italian suede with exceptional comfort, flexible construction, and timeless elegance for modern smart-casual and formal wear.",
    colors: [
            {
        color: "Cognac",
        imgs: [
"./file/30/2.avif",
"./file/30/11.avif",
"./file/30/3.avif",
"./file/30/5.avif",


        ],
        colorimg:"./file/30/20.avif",
        sizes: [
          { size: 6.5, id: 47729383276733 },
          { size: 7, id: 47729383243965 },
          { size: 8, id: 47729383211197 },
          { size: 8.5, id: 47729383178429 },
          { size: 9.5, id: 47729383735485 },
          { size: 10, id: 47729383702717 },
          { size: 11, id: 47729383669949 },
        ],
      },
            {
        color: "Slate",
        imgs: [
"./file/29/3.avif",
"./file/29/8.avif",
"./file/29/14.avif",
"./file/29/9.avif",


        ],
        colorimg:"./file/29/30.avif",
        sizes: [
          { size: 6.5, id: 47729383637181 },
          { size: 7, id: 47729383604413 },
          { size: 8, id: 47729383571645 },
          { size: 8.5, id: 47729383538877 },
          { size: 9.5, id: 47729383506109 },
          { size: 10, id: 47729383801021 },
          { size: 11, id: 47729383768253 },
        ],
      },
                  {
        color: "Brown",
        imgs: [
"./file/31/3.avif",
"./file/31/1.avif",
"./file/31/11.avif",
"./file/31/8.avif",


        ],
        colorimg:"./file/31/30.avif",
        sizes: [
          { size: 6.5, id: 47729382981821 },
          { size: 7, id: 47729382949053 },
          { size: 8, id: 47729382916285 },
          { size: 8.5, id: 47729383407805 },
          { size: 9.5, id: 47729383375037 },
          { size: 10, id: 47729383342269 },
          { size: 11, id: 47729383309501 },
        ],
      },
    ],
  },
  {
    id: 10209,
    name: "Velluto Brown",
    desc: "The essence of fine craftsmanship",
    price: 179,
    oldprice: 240,
    vare:"Essential",
    sizeguide:"./file/29/50.avif",
    listcolor:"#f8f5f0",
    material:"Premium Suede Leather",
    mainimg: "./file/31/3.avif",
    modelwearmob:"./file/31/80.avif",
    modelwearpc:"./file/31/70.avif",
    shortdesc: "Two styles. One loafer. Made to turn every look into a statement",
    longdesc: "Two styles. One loafer. Made to turn every look into a statement",
    model:"Italian Suede Loafer",
    modelimg:"./file/31/8.avif",
techdesc1:"Premium Italian suede hand-finished into a timeless tassel loafer silhouette a quiet statement of artisanal craftsmanship made for those who notice the details.",

techdesc2:"Lightweight comfort meets a breathable leather lining designed to carry you seamlessly from smart-casual days to refined evening occasions.",

Upper: "Crafted from premium, ultra-soft suede leather, featuring meticulous moc-toe stitching and a classic tassel accent that deliver a luxurious texture and a refined, elegant silhouette.",
Inner: "Fully lined with supple, breathable genuine leather that gently wraps the foot, naturally regulating temperature, reducing friction, and ensuring maximum comfort even during sockless wear.",
Insole: "Ergonomically designed genuine leather footbed with premium built-in cushioning, engineered to absorb everyday shock and provide superior support for all-day comfort.",
Outsole: "Constructed from highly flexible, ultra-lightweight rubber with a durable, anti-slip profile, offering effortless movement, agility, and a smooth, comfortable stride.",
modelname:"Tassel Loafer",
modeldesc:"Tassel Loafers are not just footwear they are a symbol of refined tradition The elegant silhouette with signature tassel detail delivers timeless sophistication and effortless confidence in every step They transition seamlessly from formal occasions to relaxed smart casual settings maintaining a polished distinguished presence Premium suede and leather craftsmanship combined with a flexible sole create everyday comfort with a luxury feel Sophisticated versatile and always timeless Tassel Loafers embody classic elegance without excess Tassel Loafers where heritage style meets enduring refinement",
title:"Vonaldo Velluto Tassel Loafer – Italian Suede Craftsmanship & Refined Luxury Style",

metadesc:"Experience understated luxury with the Vonaldo Velluto Tassel Loafer. Crafted from premium Italian suede with exceptional comfort, flexible construction, and timeless elegance for modern smart-casual and formal wear.",
    colors: [
      {
        color: "Brown",
        imgs: [
"./file/31/3.avif",
"./file/31/1.avif",
"./file/31/11.avif",
"./file/31/8.avif",
        ],
        colorimg:"./file/31/30.avif",
        sizes: [
          { size: 6.5, id: 47729382981821 },
          { size: 7, id: 47729382949053 },
          { size: 8, id: 47729382916285 },
          { size: 8.5, id: 47729383407805 },
          { size: 9.5, id: 47729383375037 },
          { size: 10, id: 47729383342269 },
          { size: 11, id: 47729383309501 },
        ],
      },
            {
        color: "Slate",
        imgs: [
"./file/29/3.avif",
"./file/29/8.avif",
"./file/29/14.avif",
"./file/29/9.avif",


        ],
        colorimg:"./file/29/30.avif",
        sizes: [
          { size: 6.5, id: 47729383637181 },
          { size: 7, id: 47729383604413 },
          { size: 8, id: 47729383571645 },
          { size: 8.5, id: 47729383538877 },
          { size: 9.5, id: 47729383506109 },
          { size: 10, id: 47729383801021 },
          { size: 11, id: 47729383768253 },
        ],
      },
                  {
        color: "Cognac",
        imgs: [
"./file/30/2.avif",
"./file/30/11.avif",
"./file/30/3.avif",
"./file/30/5.avif",


        ],
        colorimg:"./file/30/20.avif",
        sizes: [
          { size: 6.5, id: 47729383276733 },
          { size: 7, id: 47729383243965 },
          { size: 8, id: 47729383211197 },
          { size: 8.5, id: 47729383178429 },
          { size: 9.5, id: 47729383735485 },
          { size: 10, id: 47729383702717 },
          { size: 11, id: 47729383669949 },
        ],
      },
    ],
  },
  {
    id: 45871383511229,
    name: "Wesley",
    desc: "Earned its place, never asked for it",
    price: 219,
    oldprice: 300,
    vare:"New Collection",
    sizeguide:"./icons/main.webp",
    listcolor:"#f5f3ef",
    material:"Premium Genuine Leather",
    mainimg: "./file/22/50.avif",
    modelwearmob:"./file/22/20.avif",
    modelwearpc:"./file/22/10.avif",
    shortdesc: "Black penny loafer striking high cut silhouette confident presence",
    longdesc: "Statement black penny loafer with a high cut silhouette and confident presence",
    model:"Italian Leather loafer",
    modelimg:"./file/22/1.avif",
techdesc1:"Where iconic penny loafer craftsmanship meets a striking modern edge, creating a look that feels both timeless and contemporary.",
techdesc2:"Created to move comfortably through every occasion, bringing confidence, versatility, and refined style to every step.",
        Upper:"Crafted from premium genuine leather with a perfectly smooth and rich texture that naturally conforms to your foot while maintaining an elite and sophisticated appearance.",
    Inner:"Fully lined with ultra-soft calfskin leather engineered to maximize natural breathability and eliminate friction ensuring a smooth comfortable fit all day long.",
    Insole:"Features an advanced high-density cushioned leather insole that contours perfectly to your foot providing elite arch support and superior shock absorption.",
    Outsole:"A bold chunky rubber lug sole engineered to be remarkably lightweight yet highly durable featuring deep performance treads for ultimate anti-slip traction.",
    modelname:"Penny Loafer",
modeldesc:"Penny Loafers Classic Heritage Modern Confidence Penny loafers combine timeless elegance with a bold contemporary presence The iconic strap detail delivers a refined character while the elevated sole adds a modern edge that stands out naturally Designed for comfort versatility and everyday wear they transition effortlessly from smart occasions to casual moments Premium craftsmanship clean lines and a confident silhouette make them a wardrobe essential Comfortable distinctive and easy to style penny loafers offer sophistication without effort Penny loafers where classic heritage meets modern confidence",
title: "Vonaldo Wesley Penny Loafer – Premium Leather Craftsmanship & Modern Comfort.",

metadesc: "Elevate your everyday style with Vonaldo Wesley Penny Loafers, featuring premium natural leather, lightweight comfort, and a refined contemporary design inspired by Italian craftsmanship.",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/22/50.avif",
          "./file/22/17.avif",
          "./file/22/12.avif",
          "./file/22/16.avif",
          "./file/22/1.avif",
        ],
        colorimg:"./file/22/500.avif",
        sizes: [
          { size: 6, id: 47732571472061 },
          { size: 6.5, id: 47732571504829 },
          { size: 7.5, id: 47732571537597 },
          { size: 8, id: 47732571570365 },
          { size: 8.5, id: 47732571603133 },
          { size: 9, id: 47732571635901 },
          { size: 9.5, id: 47732571668669 },
        ],
      },
    ],
  },

  {
    id: 102,
    name: "Moretti",
    desc: "Modern Ease, Daily Confidence",
    price: 199,
    oldprice: 270,
    vare:"New Collection",
            sizeguide:"./icons/main.webp",
listcolor:"#f5f3ef",
    material:"Premium Genuine Leather",
    mainimg: "./file/23/1.avif",
    modelwearmob:"./file/23/30.avif",
    modelwearpc:"./file/23/20.avif",
    shortdesc: "Designed for modern lifestyles, elevated comfort, and standout",
    longdesc: "Designed for modern lifestyles crafted for elevated comfort and standout presence",
    model:"Italian Leather loafer",
    modelimg:"./file/23/12.avif",
    techdesc2:"Not your everyday loafer — the classic penny strap meets a bold modern sole. Refined, confident, unforgettable.",
    techdesc1:"A refined take on the classic penny loafer — black leather with a bold chunky sole, balancing heritage and modern presence. Polished above, purposeful below.",
    Upper:"Crafted entirely from 100% premium natural full-grain leather to provide an exceptionally durable structure and a rich sophisticated appearance that naturally adapts to your foot shape over time",
    Inner:"Fully lined with ultra-soft natural calfskin leather carefully engineered to maximize natural air circulation keeping your feet fresh cool and comfortable throughout the day",
    Insole:"Features an advanced contoured orthotic leather insole packed with high-density cushioning layers to deliver supreme arch support and exceptional shock absorption with every single step",
    Outsole:"A bold chunky platform sole made from a specialized lightweight rubber compound featuring high-performance performance treads to guarantee ultimate stability and superior anti-slip traction",
    modelname:"Penny Loafer",
modeldesc:"Penny Loafers, Classic Heritage, Modern Confidence. Timeless elegance meets a bold contemporary presence, with the iconic strap delivering refined character and the elevated sole adding a modern edge. Comfortable, versatile, and effortlessly refined, they transition naturally from smart occasions to everyday wear, making them a true wardrobe essential. Where classic heritage meets modern confidence.",
title: "Vonaldo Moretti Penny Loafer – Premium Leather Craftsmanship & Modern Comfort.",

metadesc: "Elevate your everyday style with Vonaldo Moretti Penny Loafers, featuring premium natural leather, lightweight comfort, and a refined contemporary design inspired by Italian craftsmanship.",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/23/1.avif",
          "./file/23/15.avif",
          "./file/23/10.avif",
          "./file/23/16.avif",
          "./file/23/2.avif",
          "./file/23/4.avif",
        ],
        colorimg:"./file/23/111.avif",
        sizes: [
          { size: 6, id: 47732659421373 },
          { size: 6.5, id: 47732659355837 },
          { size: 7.5, id: 47732659388605 },
          { size: 8, id: 47732659519677 },
          { size: 8.5, id: 47732659552445 },
          { size: 9, id: 47732659454141 },
          { size: 9.5, id: 47732659486909 },
        ],
      },
    ],
  },


    {
    id: 102,
    name: "Vittorio Marchetti",
    desc: "Black and white, never grey",
    price: 189,
    oldprice: 255,
    vare:"New Collection",
    sizeguide:"./file/24/50.avif",
    listcolor:"#f5f3ef",
    material:"Genuine Patent Leather",
    mainimg: "./file/24/15.avif",
    modelwearmob:"./file/24/40.avif",
    modelwearpc:"./file/24/10.avif",
    shortdesc: "Nights out to everyday moments, effortlessly put-together",
    longdesc: "From nights out to everyday moments, made to keep you looking put-together",
    model:"Italian Leather Loafer",
    modelimg:"./file/24/15.avif",
techdesc1: "Not made to blend in. Genuine leather meets a bold two-tone design, balancing classic loafer heritage with a confident modern presence. Distinctive, refined, and impossible to overlook.",
techdesc2: "From nights out to everyday moments, made to keep you put-together. Because real style means standing apart.",
    Upper:"High gloss two-tone (black and white) patent leather, accented with a premium gold-tone horsebit detail.",
    Inner:"Smooth, breathable lining designed for optimal, all-day comfort.",
    Insole:"Cushioned footbed providing exceptional support and shock absorption.",
    Outsole:"Cushioned footbed providing exceptional support and shock absorption.",
    modelname:"Loafer",
    modeldesc:"Loafers Heritage Timeless Style Modern Elegance Loafers are a key piece in refined menswear known for effortless style and lasting quality Inspired by classic heritage and updated with a modern touch they offer a balance between tradition and contemporary design Made with clean silhouettes quality materials and everyday comfort they are suitable for formal and casual wear Each pair reflects simple luxury subtle elegance and confident style making loafers an essential part of a modern wardrobe Loafers are more than footwear they represent timeless taste quiet confidence and effortless distinction where heritage meets modern elegance",
    title: "Vonaldo Vittorio Marchetti Loafer – Black & White Patent Leather Horsebit Loafer | Modern Luxury Style",
    metadesc:"Step into modern luxury with Vonaldo Vittorio Marchetti Loafers featuring high-gloss black and white patent leather premium gold horsebit detail and bold contemporary design Built for standout style and everyday confidence combining timeless loafer heritage with a fresh modern edge Perfect for smart casual looks nights out and refined daily wear where fashion meets effortless elegance",
    colors: [
      {
        color: "B-white",
        imgs: [
          "./file/24/15.avif",
          "./file/24/6.avif",
          "./file/24/9.avif",
          "./file/24/11.avif",
          "./file/24/14.avif",
          "./file/24/2.avif",
        ],
        colorimg:"./file/24/150.avif",
        sizes: [
          { size: 7.5, id: 47732699201725 },
          { size: 8, id: 47732699234493 },
          { size: 8.5, id: 47732699136189 },
          { size: 9, id: 47732699168957 },
          { size: 9.5, id: 47732699070653 },
          { size: 10.5, id: 47732699103421 },
          { size: 11, id: 47732699267261 },
          { size: 11.5, id: 47732699300029 },
        ],
      },
    ],
  },
  {
    id: 1050,
    name: "Romano Vitiello",
    desc: "Cast in silver, walked in black",
    price: 179,
    oldprice: 240,
    vare:"New Collection",
            sizeguide:"./icons/main.webp",
listcolor:"#f5f3ef",
    material:"Premium Patent Leather",
    mainimg: "./file/25/26.webp",
    modelwearmob:"./file/25/20.avif",
    modelwearpc:"./file/25/30.avif",
    shortdesc: "Designed for casual days formal nights and daily confidence",
    longdesc: "Glossy black leather with a chain detail, for casual days and formal nights",
    model:"Italian Leather Oxford",
    modelimg:"./file/25/16.webp",
    techdesc1:"Black that catches the light before it catches your eye. A chunky lug sole grounds it while a polished chain cuts through the gloss transforming classic lines into a bolder statement.",
    techdesc2:"Matte below, mirror shine above, silver in between. Some shoes complete an outfit. This one defines it.",
Upper:"High gloss patent leather paired with a signature silver chain for a bold refined presence",

Inner:"Smooth breathable lining crafted for comfort and an effortless fit",

Insole:"Comfort cushioned footbed designed to support every step with ease",

Outsole:"Chunky rubber sole delivering stability durability and confident everyday wear",
    modelname:"Chain Loafer",
modeldesc:"Chain Loafers are more than just footwear they are a bold modern statement The refined silhouette with signature chain detail gives you a confident elevated look that feels effortless all day They work for everything from smart office wear to casual nights out with a clean design that always stands out Premium materials subtle luxury and a comfortable sole make them easy to rely on Sophisticated versatile and always polished Chain Loafers give you distinction without overthinking it Chain Loafers where classic elegance meets modern edge",
            title:"Vonaldo Romano Vitiello Chain Loafer – Bold Luxury Design with Premium Polished Leather",
    metadesc:"Make a statement with the Vonaldo Romano Vitiello Chain Loafer featuring premium polished leather a signature silver chain and a modern chunky sole Built for confidence comfort and distinctive style that elevates every outfit",
    colors: [
      {
        color: "Black",
        imgs: [
          "./file/25/26.webp",
          "./file/25/17.webp",
          "./file/25/16.webp",
        ],
        colorimg:"./file/25/260.webp",
        sizes: [
          { size: 6, id: 47732741636285 },
          { size: 6.5, id: 47732741570749 },
          { size: 7.5, id: 47732741603517 },
          { size: 8, id: 47732741505213 },
          { size: 8.5, id: 47732741537981 },
          { size: 9, id: 47732741439677 },
          { size: 9.5, id: 47732741472445 },
          { size: 10.5, id: 47732741374141 },
          { size: 11, id: 47732741406909 },
        ],
      },
    ],
  },

 
 
];

export default proudct;





















      // {
      //   color: "brown",
      //   imgs: [          
      //     "./file/1.webp",
      //     "./file/2.webp",
      //     "./file/5.webp",
      //     "./file/3.webp",
      //     "./file/6.webp",
      //     "./file/7.webp",],
      //   colorimg:"./file/1.webp",
      //   sizes: [
      //     { size: 39, id: 45871363457213 },
      //     { size: 40, id: 45871363489981 },
      //     { size: 41, id: 45871363129533 },
      //     { size: 42, id: 45871363162301 },
      //     { size: 43, id: 45871363063997 },
      //     { size: 44, id: 45871363096765 },
      //   ],
      // },
